version: "3.5"
services:
    sensors:
        container_name: sensors
        image: kuiper/sensors
        environment:
            DHT22_MQTT_URL: http://172.28.1.3:1883/sensor/dht22
            BMP280_MQTT_URL: http://172.28.1.3:1883/sensor/bmp280
            VOLTAGE_MQTT_URL: http://172.28.1.3:1883/sensor/voltage
            TIME_MQTT_URL: http://172.28.1.3:1883/time/utc
            STATS_MQTT_URL: http://172.28.1.3:1883/sensor/stats
            HDC1080_MQTT_URL: http://172.28.1.3:1883/sensor/hdc1080
            INFLUX_URL: http://dbuser:password@172.28.1.4:8086/sensors
        build:
            context: .
            dockerfile: ./build/dockerfiles/sensors/Dockerfile
        depends_on:
            - mosquitto
            - influxdb
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.2

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:1.6.5
        #hostname: mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        depends_on:
            - smtp
        volumes:
            - ./build/dockerfiles/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.3

    influxdb:
        container_name: influxdb
        environment:
            INFLUXDB_DB: sensors
            INFLUXDB_ADMIN_USER: dbuser
            INFLUXDB_ADMIN_PASSWORD: password
            #INFLUXDB_HTTP_AUTH_ENABLED: "true"
        image: influxdb:latest
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        volumes:
            - /tmp/influxdb:/var/lib/influxdb
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.4

    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        environment:
            GF_SMTP_ENABLED: "true"
            GF_SMTP_HOST: "172.28.1.7:25"
            #GF_SMTP_USER: "myuser" 
            #GF_SMTP_PASSWORD: "mysecret" 
        volumes:
            - /tmp/grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - "3000:3000"
        depends_on:
            - influxdb
            - smtp
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.5

    smtp:
        container_name: smtp
        image: bytemark/smtp:latest
        ports:
            - "25:25"
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.7

    mysql:
        container_name: mysql
        build:
            context: ./build/dockerfiles/db/.
            dockerfile: ./Dockerfile
        ports:
            - "3306:3306"
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.8

    settings:
        container_name: settings
        image: kuiper/settings
        environment:
            PORT: "8081"
            DB_CONN: "root:password@tcp(172.28.1.8)/device_settings?charset=utf8&parseTime=True&loc=Local"
            BAT_CAVE_MQTT_URL: "http://172.28.1.3:1883/bc/settings"
            WAIT_HOSTS: "mysql:3306"
            WAIT_HOSTS_TIMEOUT: "300"
            WAIT_SLEEP_INTERVAL: "30"
            WAIT_HOST_CONNECT_TIMEOUT: "30"
        build:
            context: .
            dockerfile: ./build/dockerfiles/settings/Dockerfile
        depends_on:
            - mosquitto
            - mysql
        command: sh -c "/wait"
        ports:
            - "8081:8081"
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.9

    apigateway:
        container_name: apigateway
        image: kuiper/apigateway
        environment:
            PORT: "9090"
            SETTINGS_HOST: "172.28.1.9:8081"
        build:
            context: .
            dockerfile: ./build/dockerfiles/apigateway/Dockerfile
        depends_on:
            - settings
        ports:
            - "9090:9090"
        networks:
            kuiper_net:
                ipv4_address: 172.28.1.10

networks:
    kuiper_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/24
