version: "3.5"
services:
    app:
        environment:
            DHT22_MQTT_URL: http://172.28.1.3:1883/sensor/dht22
            BMP280_MQTT_URL: http://172.28.1.3:1883/sensor/bmp280
            VOLTAGE_MQTT_URL: http://172.28.1.3:1883/sensor/voltage
            TIME_MQTT_URL: http://172.28.1.3:1883/time/utc
            STATS_MQTT_URL: http://172.28.1.3:1883/sensor/stats
            INFLUX_URL: http://dbuser:password@172.28.1.4:8086/iota
        build:
            context: .
            dockerfile: ./build/dockerfiles/app/Dockerfile
        depends_on:
            - mosquitto
            - influxdb
        networks:
            iota_net:
                ipv4_address: 172.28.1.2

    mosquitto:
        image: eclipse-mosquitto:1.6.5
        #hostname: mosquitto
        container_name: mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./build/dockerfiles/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            iota_net:
                ipv4_address: 172.28.1.3

    influxdb:
        environment:
            INFLUXDB_DB: iota 
            INFLUXDB_ADMIN_USER: dbuser
            INFLUXDB_ADMIN_PASSWORD: password
            #INFLUXDB_HTTP_AUTH_ENABLED: "true"
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        volumes:
            - /tmp/influxdb:/var/lib/influxdb
        networks:
            iota_net:
                ipv4_address: 172.28.1.4

    grafana:
        image: grafana/grafana:latest
        volumes:
            - /var/grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - "3000:3000"
        networks:
            iota_net:
                ipv4_address: 172.28.1.5

    smtp:
      image: namshi/smtp:latest
      ports:
          - "25:25"
      networks:
        iota_net:
              ipv4_address: 172.28.1.7

    mysql:
      build:
          context: ./build/dockerfiles/db
          dockerfile: ./build/dockerfiles/db/Dockerfile
      ports:
          - "3306:3306"
      networks:
          iota_net:
              ipv4_address: 172.28.1.8

    settings:
      environment:
          PORT: 8080
          DB_CONN: root:password@tcp(172.28.1.8)/device_settings
          BAT_CAVE_MQTT_URL: http://172.28.1.3:1883/bc/settings
      build:
          context: .
          dockerfile: ./build/dockerfiles/settings/Dockerfile
      depends_on:
          - mysql
      ports:
          - "8080:8080"
      networks:
          iota_net:
              ipv4_address: 172.28.1.9

networks:
    iota_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/24
