version: "3.5"
services:
    app:
        environment:
            INDOOR_HUMIDITY_MQTT_URL: http://172.28.1.3:1883/indoor/humidity
            INFLUX_URL: http://dbuser:password@172.28.1.4:8086/home_sensors
        build:
            context: .
            dockerfile: ./build/dockerfiles/app/Dockerfile
        depends_on:
            - mosquitto
            - influxdb
        networks:
            iota_net:
                ipv4_address: 172.28.1.2

    mosquitto:
        image: eclipse-mosquitto
        #hostname: mosquitto
        container_name: mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./build/dockerfiles/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            iota_net:
                ipv4_address: 172.28.1.3

    influxdb:
        environment:
            INFLUXDB_DB: home_sensors
            INFLUXDB_ADMIN_USER: dbuser
            INFLUXDB_ADMIN_PASSWORD: password
            #INFLUXDB_HTTP_AUTH_ENABLED: "true"
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        #volumes:
            #- /tmp/influxdb:/var/lib/influxdb
        networks:
            iota_net:
                ipv4_address: 172.28.1.4

    grafana:
        image: grafana/grafana:latest
        #volumes:
            #- ./grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - "3000:3000"
        networks:
            iota_net:
                ipv4_address: 172.28.1.5

networks:
    iota_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/24
