version: "3.5"
services:
    app:
        environment:
            MQTT_URL=http://172.28.1.2:1883/test
            INFLUX_URL=http://dbuser:password@172.28.1.3:8086/sensors
        build:
            context: ./build/dockerfiles/app
            dockerfile: Dockerfile
        depends_on:
            - mosquitto
            - influxdb

    mosquitto:
        image: eclipse-mosquitto
        #hostname: mosquitto
        container_name: mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./build/dockerfiles/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            iota_net:
                ipv4_address: 172.28.1.2

    influxdb:
        environment:
            INFLUXDB_DB: sensors
            INFLUXDB_ADMIN_USER: dbuser
            INFLUXDB_ADMIN_PASSWORD: password
            #INFLUXDB_HTTP_AUTH_ENABLED: "true"
        image: influxdb:latest
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        #volumes:
            #- /tmp/influxdb:/var/lib/influxdb
        networks:
            iota_net:
                ipv4_address: 172.28.1.3

networks:
    iota_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.1.0/24
